# Generated by Django 3.0 on 2020-12-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdtBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_brand_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='CdtColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('bl_primary', models.BooleanField(default=False, verbose_name='Primary')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='CdtVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_vendor', models.CharField(max_length=50, verbose_name='Vendor')),
                ('nm_phone_number_vendor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('tx_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='TdtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_product_name', models.CharField(max_length=75, verbose_name='Product Name')),
                ('tx_description', models.TextField(max_length=300, verbose_name='Description')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.CdtBrand')),
                ('id_color', models.ManyToManyField(to='form_app.CdtColor')),
                ('id_photo', models.ManyToManyField(to='form_app.CdtProductPhoto')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.CdtVendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
