# Generated by Django 3.0 on 2020-12-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=4, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='TdtSkuProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=75, verbose_name='Sku')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'SKU Product',
                'verbose_name_plural': 'SKU Products',
            },
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_color',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_photo',
        ),
        migrations.DeleteModel(
            name='CdtColor',
        ),
        migrations.DeleteModel(
            name='CdtProductPhoto',
        ),
        migrations.AddField(
            model_name='tdtskuproduct',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_app.TdtProduct'),
        ),
        migrations.AddField(
            model_name='tdtskuproduct',
            name='id_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_app.CdtSize'),
        ),
    ]
